events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 8000;
        # server_name your.server.name.com;

        # SSL certificates
        # ssl_certificate /etc/nginx/ssl/certificate.cer;
        # ssl_certificate_key /etc/nginx/ssl/certificate.key;

        # ssl_protocols TLSv1.2 TLSv1.3;
        # ssl_prefer_server_ciphers on;

        # Serve Angular application
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html =404;
        }
    }
}